apiVersion: v1
kind: Secret
metadata:
  name: mattermost-postgres
  namespace: mattermost
type: Opaque
stringData:
  DB_CONNECTION_CHECK_URL: postgres://YOUR_POSTGRES_USER:YOUR_POSTGRES_PASSWORD@YOUR_POSTGRES_SERVER.postgres.database.azure.com/mattermost?sslmode=require
  DB_CONNECTION_STRING: postgres://YOUR_POSTGRES_USER:YOUR_POSTGRES_PASSWORD@YOUR_POSTGRES_SERVER.postgres.database.azure.com/mattermost?sslmode=require
