apiVersion: v1
kind: Secret
metadata:
  name: mattermost-postgres
  namespace: mattermost
type: Opaque
stringData:
  DB_CONNECTION_STRING: "postgres://YOUR_POSTGRES_ADMIN_USER:YOUR_POSTGRES_ADMIN_PASSWORD@YOUR_POSTGRES_SERVER.postgres.database.azure.com:5432/mattermost?sslmode=require"
