apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: mattermost-minio
type: Opaque
stringData:
  config.env: |
    export MINIO_ROOT_USER="YOUR_MINIO_ADMIN_USER"
    export MINIO_ROOT_PASSWORD="YOUR_MINIO_ADMIN_PASSWORD"
